### ISSUE TITLE
Getting error: failed to load source for a dependency on `litcrypt`

### ISSUE THREAD

**Issue by munjalpatel** [anvie/litcrypt.rs#1]
Hello I am trying to use this in my project.

However, doing `cargo run` gives me the following error:
![image](https://user-images.githubusercontent.com/2717686/32629210-45bbe9f0-c54d-11e7-936d-c2e3a33bfcab.png)

I have aded this in my ___Cargo.toml___

    [dependencies]
    litcrypt = { git = "https://github.com/anvie/litcrypt.rs" }
    xor = { git = "https://github.com/anvie/xor-rs" }

Here is my ___main.rs___

    fn main() {
        println!("{}", lc!("Hello, from Rust!"));
    }

**Comment by anvie** [comment]
What Cargo & Rust version do you use?

**Comment by munjalpatel** [comment]
I installed Rust yesterday. So the latest version of Rust and Cargo.

```
>>> rustc --version
rustc 1.21.0 (3b72af97e 2017-10-09)

>>> cargo --version
cargo 0.22.0 (3423351a5 2017-10-06)
```

**Comment by anvie** [comment]
Please clone with recursive: `git clone --recursive https://github.com/anvie/litcrypt.rs`

**Comment by anvie** [comment]
Should fixed now, please pull from the latest master branch.
