### ISSUE TITLE
setting the env variable dont work on win

### ISSUE THREAD

**Issue by FU3X** [anvie/litcrypt.rs#16]
export LITCRYPT_ENCRYPT_KEY=
&
set LITCRYPT_ENCRYPT_KEY=

i tried doing this on windows

**Comment by FoxesChooseJiff** [comment]
Just use the environmental variables dialog under system properties -> advanced -> environmental variables

**Comment by anvie** [comment]
@FU3X if U are using Power Shell type like this:

```
$env:LITCRYPT_ENCRYPT_KEY = 'mys3cr3tkey'
```
