### ISSUE TITLE
Nothing works all the dependencies are missing 

### ISSUE THREAD

**Issue by ta3pks** [anvie/litcrypt.rs#2]

**Comment by virtualritz** [comment]
```rust
extern crate rustc_driver;
extern crate rustc_expand;
extern crate rustc_ast;
extern crate rustc_span;

use rustc_ast::{
    ast::LitKind,
    token::{self, TokenKind},
    tokenstream::TokenTree,
};
use rustc_driver::plugin::Registry;
use rustc_expand::base::{DummyResult, ExtCtxt, MacEager, MacResult};
use rustc_span::{symbol::Ident, Span};

use std::{env, rc::Rc};
```

Should fixe the deps., I think.

But there are other issues that need addressing because stuff changed.

This crate looks very useful. It would be great if it got updated & published on `crates.io`.

**Comment by anvie** [comment]
Sorry for the delay, I just fixed this issue, please pull from the latest master branch, now should work on both stable and nightly Rust.

Please refer to the new documentation for usage.

@virtualritz here you go: https://crates.io/crates/litcrypt

**Comment by virtualritz** [comment]
Fantastic! Thanks heaps. 👍

**Comment by virtualritz** [comment]
> Please refer to the new documentation for usage.

@anvie The [new docs](https://docs.rs/litcrypt/0.2.0/litcrypt/) look empty.

**Comment by virtualritz** [comment]
I am copying & copywriting the resp. sections of the `README` into the code and will open a PR soon.

**Comment by virtualritz** [comment]
[Done](https://github.com/anvie/litcrypt.rs/pull/3).
