### ISSUE TITLE
it's posible use lc! inside modules?

### ISSUE THREAD

**Issue by jjmatilla** [anvie/litcrypt.rs#6]
when I try in main works, but when I use in a module it isn't working.

What I 'm doing wrong:

![image](https://user-images.githubusercontent.com/67703322/132418082-684e105f-5d58-48c0-a589-b984bed59668.png)

Thank you!

rustc 1.51
![image](https://user-images.githubusercontent.com/67703322/132418264-6e3b0d08-21db-46a8-acb7-6faf941658eb.png)
![image](https://user-images.githubusercontent.com/67703322/132418272-e06e6282-8ef4-4b23-9bcc-759a7c963937.png)

**Comment by anvie** [comment]
Could you please post the compiler output?

**Comment by jjmatilla** [comment]
![image](https://user-images.githubusercontent.com/67703322/132493064-a2f9cdef-d43f-4c2d-a24c-fefa705179a7.png)
[pruebalitcrypt.zip](https://github.com/anvie/litcrypt.rs/files/7128121/pruebalitcrypt.zip)

**Comment by anvie** [comment]
Please give it a try using latest commit, version 0.3.0 (not yet published on crates.io), this is breaking changes,  so you need to make a little changes in your program, see latest example or README for the changes.

let me know if this fixed the issue.

**Comment by jjmatilla** [comment]
![image](https://user-images.githubusercontent.com/67703322/132770238-46e27df5-3307-46b5-b197-915171a3af31.png)

Thank you!
