### ISSUE TITLE
Windows use

### ISSUE THREAD

**Issue by RaquisDawLn** [anvie/litcrypt.rs#8]
When using

#[macro_use]
extern crate litcrypt;

use_litcrypt!();

fn main(){
    println!("his name is: {}", lc!("Voldemort"));
}

and using the command "export LITCRYPT_ENCRYPT_KEY="myverysuperdupermegaultrasecretkey"" i get this response, 

export LITCRYPT_ENCRYPT_KEY="myverysuperdupermegaultrasecretkey"
export : The term 'export' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At line:1 char:1
+ export LITCRYPT_ENCRYPT_KEY="myverysuperdupermegaultrasecretkey"
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (export:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
    Then i tried this since i seen a repo of someone using litcrypt and had it like this,
    
    #[macro_use]
extern crate litcrypt;

use_litcrypt!("myverysuperdupermegaultrasecretkey");

fn main(){
    println!("his name is: {}", lc!("Voldemort"));
}

I get a response saying that the key is not set, i am unsure what im doing incorrect and would really love some help to figure this out
Error when running with key on line 4
help: message: LITCRYPT_ENCRYPT_KEY environment variable not set.

**Comment by anvie** [comment]
In Windows you should set environment variable from System settings, please take a look at this tutorial how to set environment variable in Windows: https://www.computerhope.com/issues/ch000549.htm
